---

packages: 
  - { name: clipy, state: present }
  - { name: docker, state: present }
  - { name: google-chrome, state: present }
  - { name: google-japanese-ime, state: present }
  - { name: iterm2, state: present }
  - { name: karabiner-elements, state: present }
  - { name: kindle, state: present }
  - { name: microsoft-word, state: present }
  - { name: microsoft-excel, state: present }
  - { name: microsoft-powerpoint, state: present }
  - { name: slack, state: present }
  - { name: visual-studio-code, state: present }
